version: '3.9'
services:
  sandbox:
    build: .
    init: true
    volumes:
      - ../:/workspaces/sandbox
      - ~/.gitconfig:/home/sandbox/.gitconfig
      - home_dir:/home/sandbox
    command: ["sleep", "infinity"]

volumes:
  home_dir:
