version: '3.9'
services:
  sandbox:
    build: .
    init: true
    volumes:
      - ../:/home/sandbox/workdir
      - ~/.gitconfig:/home/sandbox/.gitconfig
      - homedir:/home/sandbox
    command: ["sleep", "infinity"]
volumes:
  homedir:
