version: "3.9"
services:
  sandbox:
    build:
      context: .
      args:
        USER_ID: ${HOST_USER_ID}
        GROUP_ID: ${HOST_GROUP_ID}
        USER_NAME: ${USER}
    init: true
    working_dir: /workspaces/src
    volumes:
      - .:/workspaces/src
      - ~/.gitconfig:/home/${USER}/.gitconfig:ro
      - ~/.config/gh:/home/${USER}/.config/gh:ro
      - home_dir:/home/${USER}
      - ~/.tmux/sessions:/home/${USER}/.tmux/sessions
    environment:
      - TMUX=$TMUX
    command: ["sh", "-c", "/workspaces/src/init.sh && sleep infinity"]

volumes:
  home_dir:
