version: '3.9'
services:
  sandbox:
    build:
      context: .
      args:
        USER_ID: ${HOST_USER_ID}
        GROUP_ID: ${HOST_GROUP_ID}
    init: true
    working_dir: /workspaces/src
    volumes:
      - .:/workspaces/src
      - ~/.gitconfig:/home/sandbox/.gitconfig:ro
      - ~/.config/gh:/home/sandbox/.config/gh:ro
      - home_dir:/home/sandbox
      - /tmp/tmux-1000:/tmp/tmux-1000
    environment:
      - TMUX=$TMUX
    command: [ "sh" , "-c", "/workspaces/src/init.sh && sleep infinity"]

volumes:
  home_dir:
