[keyboard]
bindings = [
  {key = "c", mods = "Control|Shift", action = "Copy"},
  {key = "v", mods = "Control|Shift", action = "Paste"},
  {key = ".", mods = "Control", chars = "\u0003"},
  {key = "n", mods = "Control|Shift", action = "CreateNewWindow"},
]
