[keyboard]
bindings = [
  {key = "c", mods = "Control", action = "Copy"},
  {key = "v", mods = "Control", action = "Paste"},
  {key = ".", mods = "Control", chars = "\u0003"},
  {key = "+", mods = "Control", action = "IncreaseFontSize"},
  {key = "=", mods = "Control", action = "IncreaseFontSize"},
  {key = "-", mods = "Control", action = "DecreaseFontSize"},
  {key = "n", mods = "Control|Shift", action = "CreateNewWindow"},
]
