# for windows
[general]
import = [
  "extensions/iceberg.toml",
  "extensions/keybinding.toml",
  "extensions/window.toml",
]

[env]
TERM = "alacritty"
WSLENV = "TERM"

[terminal.shell]
program = "/Windows/System32/wsl.exe --cd ~"

[font]
size = 11

