# for windows

[general]
import = [
  "extensions/iceberg.toml",
  "extensions/keybinding.toml",
]

[env]
TERM = "alacritty"
WSLENV = "TERM"

[terminal.shell]
program = "/Windows/System32/wsl.exe --cd ~"

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.93

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 10

