[tools]
claude = "latest"
helix = "latest"
fzf = "latest"
zoxide = "latest"
delta = "latest"
"github:SuperCuber/dotter" = "latest"
ghq = "latest"
yazi = "latest"
"github:googleworkspace/cli" = "latest"
gcloud = "latest"
lazygit = "latest"
rust = { version = "latest", os = ["linux"] }
"cargo:xremap" = { version = "latest", os = ["linux"] }
"npm:@google/jules" = { version = "latest", os = ["linux"] }
