[tools]
helix = "latest"
fzf = "latest"
zoxide = "latest"
delta = "latest"
"github:SuperCuber/dotter" = "latest"
"ubi:ogulcancelik/herdr" = "latest"
ghq = "latest"
yazi = "latest"
"github:googleworkspace/cli" = "latest"
"github:rtk-ai/rtk" = "latest"
gcloud = "latest"
lazygit = "latest"
jq = "latest"
node = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
rust = { version = "latest", os = ["linux"] }
"cargo:xremap" = { version = "latest", os = ["linux"] }
"npm:@google/jules" = { version = "latest", os = ["linux"] }
