#!/bin/sh

subcommand=$1
url=$(git config --get remote.origin.url | sed 's/\.git$//')

case $subcommand in
  link)
    commit_hash=$(git rev-parse HEAD)
    file_path=$2
    line_number=$3

    # リポジトリ配下ならどのディレクトリから呼んでもルート相対パスに解決する
    toplevel=$(git rev-parse --show-toplevel)
    case $file_path in
      /*) abs_path=$file_path ;;
      *)  abs_path="$(pwd)/$file_path" ;;
    esac
    rel_path=${abs_path#"$toplevel"/}

    echo "${url}/blob/$commit_hash/${rel_path}#L${line_number}"
    ;;
  pr)
    line_number=$2
    echo "${url}/pull/${line_number}"
    ;;
  *)
    echo "invalid subcommand: $subcommand"
    ;;
esac

