#!/bin/bash
# https://github.com/craftzdog/dotfiles-public/blob/0ea8ead000014cd71ae0a429cc6cf87468974732/.scripts/ide
tmux split-window -v -l 30%
tmux split-window -h -l 66%
tmux split-window -h -l 50%
