#!/bin/bash

docker run -it --rm \
  -u $USER \
  -v .:/workspaces/src \
  -v codecraft_home:/home/$USER \
  -v $TMUX_TMPDIR:$TMUX_TMPDIR \
  -v ~/.gitconfig:/home/$USER/.gitconfig:ro \
  -v ~/.config/gh:/home/$USER/.config/gh:ro \
  -w /workspaces/src \
  -e TMUX=$TMUX \
  codecraft \
  nvim --listen /tmp/nvim-server.pipe $@

