#!/bin/bash

mode=$1
mkdir -p ~/.config
rm -f ~/.config/nvim

case "$mode" in
"lazyvim")
	ln -s "$SCRIPT_DIR/settings/lazyvim" ~/.config/nvim
	;;
"zenvim")
	ln -s "$SCRIPT_DIR/settings/zenvim" ~/.config/nvim
	;;
*)
	echo "$mode isn't supported."
	;;
esac
