#!/bin/zsh
# TODO change to variable path
WORKSPACE_DIR="/workspaces/src"

mode=$1

case "$mode" in
"lazyvim")
	mkdir -p ~/.config
	rm -f ~/.config/nvim
	ln -s "$WORKSPACE_DIR/settings/lazyvim" ~/.config/nvim
	;;
"zenvim")
	mkdir -p ~/.config
	rm -f ~/.config/nvim
	ln -s "$WORKSPACE_DIR/settings/zenvim" ~/.config/nvim
	;;
*)
	echo "$mode isn't supported."
	;;
esac
