keypress_delay_ms: 20
virtual_modifiers:
  - CapsLock
# key to key
modmap:
  - name: Global
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Enter
      KEY_RIGHTALT:
        held: CapsLock
        alone: Enter
      Enter:
        held: Ctrl_R
        alone: Henkan
      Alt_L:
        held: Alt_L
        alone: Muhenkan
      Semicolon: Enter

# key combination to key combination
keymap:
  - name: Launch
    remap:
      Ctrl-Alt-t:
        launch: ["/usr/bin/wezterm"]
  - name: Global
    remap:
      Alt-w: Alt-tab
      CapsLock-i: Up
      CapsLock-j: Left
      CapsLock-k: Down
      CapsLock-l: Right
      Ctrl_L-Enter: Semicolon
      Shift-Enter: Shift-Semicolon
      # for slack
      Alt-Enter: Ctrl_L-Enter
      Ctrl-CapsLock-j: Home
      Ctrl-CapsLock-l: End
